# name: Publish packages & Deploy storybook

# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup Node
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14.x
#           yarn: true
#           registry-url: https://registry.npmjs.org
#       - name: Install dependencies & Build
#         run: yarn && yarn build
#       - name: Publish packages on NPM
#         run: yarn run publish
#         env:
#           NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
